-- けいさんクエスト用 Supabase 初期設定
-- Supabase Dashboard > SQL Editor に貼り付けて実行する。

create table if not exists public.results (
    id bigint generated by default as identity primary key,
    played_at timestamptz not null default now(),
    player text not null,
    level integer not null check (level between 1 and 10),
    correct_count integer not null check (correct_count between 0 and 10),
    question_count integer not null default 10,
    accuracy numeric not null,
    total_time numeric not null,
    average_time numeric not null,
    best_time numeric not null
);

create index if not exists results_player_idx
    on public.results(player);

create index if not exists results_player_level_idx
    on public.results(player, level);

create table if not exists public.collections (
    id bigint generated by default as identity primary key,
    player text not null,
    creature_id text not null,
    count integer not null default 1 check (count >= 1),
    first_acquired timestamptz not null default now(),
    last_acquired timestamptz not null default now(),
    constraint collections_player_creature_unique unique(player, creature_id)
);

create index if not exists collections_player_idx
    on public.collections(player);

-- 家庭内の簡易アプリとして、匿名キーからの読み書きを許可する設定。
-- 個人情報や本名は保存しないことを推奨する。
alter table public.results enable row level security;
alter table public.collections enable row level security;

drop policy if exists "results_read_all" on public.results;
create policy "results_read_all"
on public.results
for select
to anon
using (true);

drop policy if exists "results_insert_all" on public.results;
create policy "results_insert_all"
on public.results
for insert
to anon
with check (true);

drop policy if exists "collections_read_all" on public.collections;
create policy "collections_read_all"
on public.collections
for select
to anon
using (true);

drop policy if exists "collections_insert_all" on public.collections;
create policy "collections_insert_all"
on public.collections
for insert
to anon
with check (true);

drop policy if exists "collections_update_all" on public.collections;
create policy "collections_update_all"
on public.collections
for update
to anon
using (true)
with check (true);
